### ISSUE TITLE
Documentation example when discovery is being call from the server side

### ISSUE THREAD

**Issue by wilsonwong13** [watson-developer-cloud/discovery-components#154]
Currently, to preview the demo the user needs to run the application localhost and curl the bearer token. But this is not feasible for real application because discovery cannot be used on the client-side due to CORS. Would like to see an example on how to run the demo when discovery is being called from the server-side

**Comment by maniax89** [comment]
right - i think if you are building the client-side application assets then just run the server, you wouldn't have cors issues ->

```
yarn workspace discovery-search-app build
yarn workspace discovery-search-app run server
```
then open `localhost:4000` and you shouldn't see cors issues anymore

**Comment by jhpedemonte** [comment]
The example app is set up to proxy Discovery API calls through the UI server (see https://github.com/watson-developer-cloud/discovery-components/blob/master/examples/discovery-search-app/src/setupProxy.js). This achieves two things:
1. No CORS issues, since the client code is sending requests to the UI server on the same domain.
2. No leaking of credentials, since the UI server adds the authorization header (and that is hidden from the client code).
